path: "../Strukturen/"
name.already.exist: "Dieser Name existiert bereits!!"
save.wrong.usage: "Falsche Werte!! Benutze /structure save <x> <y> <z> <x1> <y1> <z1> <name>"
place.wrong.usage: "Falsche Werte!! Benutzte /structure place <x> <y> <z> <rotation (0°/90°/180°/270°/360°)> <name>"
wrong.subcommand: "Dieser Unterbefehl existiert nicht!"
place.tabcompletor: "<x> <y> <z> <rotation (0°/90°/180°/270°/360°)> <name>"
save.tabcompletor: "<x> <y> <z> <x1> <y1> <z1> <name>"
place.success: "Strucktur erfolgreich platziert!"
save.success: "Strucktur erfolgreich gespeichert!"